skanmark/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('engineers', 'EngineerController');
Route::resource('categories', 'CategoryController');
Route::resource('calendars', 'CalendarController');
Route::resource('timeoptions', 'TimeoptionController');

Route::get('/appointments/timeoptions','AppointmentController@timeoption')->name('appointments.timeoption'); //it should be before appointments
Route::resource('appointments', 'AppointmentController');


//only admin can access
Route::middleware(['admin'])->group(function () {           
   Route::resource('roles', 'RoleController');
});

skanmark/app/Calendar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Calendar extends Model
{
    //

    protected $fillable = [
        'date','timeoption','user_id','category_id',
    ];

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function categories(){
        return $this->belongsTo('App\Calendar');
    }

    public function appointments(){
        return $this->hasMany('App\Appointment');
    }

    public function timeoptions(){
        return $this->hasMany('App\Timeoption');
    }
}

skanmark/app/Http/Controllers/CalendarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Responses\Calendars\CalendarIndexResponse;
use App\Http\Responses\Calendars\CalendarCreateResponse;
use App\Http\Responses\Calendars\CalendarStoreResponse;
use App\Http\Responses\Calendars\CalendarDestroyResponse;
use App\Calendar;


class CalendarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return new CalendarIndexResponse();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return new CalendarCreateResponse();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        return new CalendarStoreResponse($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Calendar  $calendar
     * @return \Illuminate\Http\Response
     */
    public function show(Calendar $calendar)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Calendar  $calendar
     * @return \Illuminate\Http\Response
     */
    public function edit(Calendar $calendar)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Calendar  $calendar
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Calendar $calendar)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Calendar  $calendar
     * @return \Illuminate\Http\Response
     */
    public function destroy(Calendar $calendar)
    {
        return new CalendarDestroyResponse($calendar);
      // print_r(Calendar::find($calendar->id)->toJson());
    }  
}

skanmark/resources/views/calendars/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create Dates') }}<a href="/calendars" style="float:right;">&lArr; Back</a></div>

                <div class="card-body">
                    <form method="POST" action="{{ Route('calendars.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="category_id" class="col-md-4 col-form-label text-md-right">{{ __('Select Category') }}</label>
                            <div class="col-md-6">
                                <select name="category_id" class="form-control">
                                    @foreach ($categories as $c)
                                        <option value="{{$c->id}}">{{$c->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="date" class="col-md-4 col-form-label text-md-right">{{ __('Date') }}</label>

                            <div class="col-md-6">
                                <input type="date" class="form-control" name="date" value="{{date('Y-m-d')}}" required>
                            </div>
                        </div>                       
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

skanmark/resources/views/calendars/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
       @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
      <ul class="list-group">
          <div class="list-group-item d-flex justify-content-between align-items-center">Click date to add Timeoption<span><a href="calendars/create">+ CREATE NEW DATE</a></span></div>
          @foreach ($dates as $date)
            <li class="list-group-item">
                <a href="{{ route('timeoptions.create', ['calendar_id'=> $date->id, 'date'=> $date->date]) }}">{{$date->date}}</a>
                <span class="float-right">
                  <a href="calendars/{{$date->id}}/edit" class="btn btn-outline-secondary btn-sm" style="padding:1px 1px; margin-right:10px;">&#9998; Edit</a><a href="#" class="btn btn-outline-danger btn-sm" style="padding:1px 1px;" onclick="deleteDate()">&#10008; Delete</a>
                </span>
              <form id="delete-form" action="{{ route('calendars.destroy', [$date->id]) }}" method ="POST" style="display: none;">
                <input type="hidden" name="_method" value="delete">
              {{csrf_field()}}
              </form>
            </li>
          @endforeach
      </ul>
    </div>
  </div>
</div>
@endsection

<script type="text/javascript">
  function deleteDate(){
    var result=confirm('Are you sure you wish to delete this item?');
    if(result){
        event.preventDefault();
        document.getElementById('delete-form').submit();
    }
  }
</script>