skanmark/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('engineers', 'EngineerController');
Route::resource('categories', 'CategoryController');
Route::resource('calendars', 'CalendarController');
Route::resource('timeoptions', 'TimeoptionController');

Route::get('/appointments/timeoptions','AppointmentController@timeoption')->name('appointments.timeoption'); //it should be before appointments
Route::resource('appointments', 'AppointmentController');


//only admin can access
Route::middleware(['admin'])->group(function () {           
   Route::resource('roles', 'RoleController');
});

skanmark/app/Http/Controllers/EngineerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Hash;
use App\Http\Responses\Engineers\EngineerIndexResponse;
use App\Http\Responses\Engineers\EngineerCreateResponse;
use App\Http\Responses\Engineers\EngineerShowResponse;
use App\Http\Responses\Engineers\EngineerEditResponse;
use App\Http\Responses\Engineers\EngineerUpdateResponse;
use App\Http\Responses\Engineers\EngineerDestroyResponse;
use Illuminate\Http\Request;
use App\User;


class EngineerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return new EngineerIndexResponse();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return new EngineerCreateResponse();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Engineer  $engineer
     * @return \Illuminate\Http\Response
     */
    public function show(User $engineer)
    {
        //
        return new EngineerShowResponse($engineer);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Engineer  $engineer
     * @return \Illuminate\Http\Response
     */
    public function edit(User $engineer)
    {
        //
        return new EngineerEditResponse($engineer);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Engineer  $engineer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $engineer)
    {
        //
        return new EngineerUpdateResponse($engineer);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Engineer  $engineer
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $engineer)
    {
        //
        return new EngineerDestroyresponse($engineer);
    }
}

skanmark/resources/views/engineers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register Engineer') }}<a href="/engineers" style="float:right;">&lArr; Back</a></div>

                <div class="card-body">
                    <form method="POST" action="{{ Route('register') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>
                        <div><input type="hidden" name='role_id' value='2'></div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

skanmark/resources/views/engineers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Engineer') }}<a href="/engineers" style="float:right;">&lArr; Back</a></div>

                <div class="card-body">
                    <form class="form-horizontal" method="POST" action="{{ route('engineers.update',[$engineer->id]) }}">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="put">

                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name" class="col-md-4 control-label">Name</label>
                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control" name="name" value="{{ $engineer->name }}" required>
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Edit
                        </button>
                    </div>
                </div>
            </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

skanmark/resources/views/engineers/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
       @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
      <ul class="list-group">
          <div class="list-group-item d-flex justify-content-between align-items-center">Engineers<span><a href="engineers/create">+ CREATE NEW ENGINEER</a></span></div>
          @foreach ($engineers as $engineer)
            <li class="list-group-item">
                <a href="engineers/{{$engineer->id}}">{{$engineer->name}}</a>
                <span class="float-right">
                  <a href="engineers/{{$engineer->id}}/edit" class="btn btn-outline-secondary btn-sm" style="padding:1px 1px; margin-right:10px;">&#9998; Edit</a><a href="#" class="btn btn-outline-danger btn-sm" style="padding:1px 1px;" onclick="deleteEngineer()">&#10008; Delete</a>
                </span>
              <form id="delete-form" action="{{ route('engineers.destroy', [$engineer->id]) }}" method ="POST" style="display: none;">
                <input type="hidden" name="_method" value="delete">
              {{csrf_field()}}
              </form>
            </li>
          @endforeach
      </ul>
    </div>
  </div>
</div>
@endsection

<script type="text/javascript">
  function deleteEngineer(){
    var result=confirm('Are you sure you wish to delete this item?');
    if(result){
        event.preventDefault();
        document.getElementById('delete-form').submit();
    }
  }
</script>

skanmark/resources/views/engineers/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
        @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
         <table class="table">
            <thead>
              <tr>
                <th scope="col">Engineer detail</th>
                <th scope="col"><a href="/engineers">&lArr; Back</a></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">Name</th>
                <td>{{$engineer->name}}</td>
              </tr>
              <tr>
                <th scope="row">Email</th>
                <td>{{$engineer->email}}</td>
              </tr>
              <tr>
                <th scope="row">Created at</th>
                <td>{{$engineer->created_at}}</td>
              </tr>
              <tr>
                <th scope="row">Updated at</th>
                <td>{{$engineer->updated_at}}</td>
              </tr>
            </tbody>
          </table>
      </div>
  </div>
</div>
@endsection